# Generated by Django 4.2.7 on 2025-05-15 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.CharField(default='MH001', max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Mã môn học')),
                ('name', models.CharField(default='Môn học mặc định', max_length=200, verbose_name='Tên môn học')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('credits', models.PositiveIntegerField(default=3, verbose_name='Số tín chỉ')),
                ('faculty', models.CharField(choices=[('cntt', 'Công nghệ thông tin'), ('kt', 'Kinh tế'), ('nn', 'Ngoại ngữ'), ('kh', 'Khoa học xã hội'), ('khac', 'Khác')], default='cntt', max_length=50, verbose_name='Khoa')),
                ('status', models.CharField(choices=[('active', 'Đang hoạt động'), ('inactive', 'Không hoạt động'), ('pending', 'Đang chờ duyệt')], default='active', max_length=20, verbose_name='Trạng thái')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subjects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Môn học',
                'verbose_name_plural': 'Môn học',
                'ordering': ['name'],
                'permissions': [('can_view_subject_details', 'Có thể xem thông tin môn học'), ('can_manage_subject', 'Có thể quản lý môn học'), ('can_view_subject_scores', 'Có thể xem điểm môn học'), ('can_manage_subject_scores', 'Có thể quản lý điểm môn học')],
            },
        ),
    ]
