# Generated by Django 4.2.7 on 2025-05-19 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_semester', '0001_initial'),
        ('app_subject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_semester.semester', verbose_name='Học kỳ'),
        ),
    ]
