# Generated by Django 4.2.7 on 2025-05-20 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0002_alter_user_options_user_address_user_is_deleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_semester', '0002_alter_semester_options_semester_is_deleted_and_more'),
        ('app_subject', '0002_subject_semester'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name'], 'permissions': [('can_view_subject_details', 'Có thể xem thông tin môn học'), ('can_manage_subject', 'Có thể quản lý môn học'), ('can_view_subject_scores', 'Có thể xem điểm môn học'), ('can_manage_subject_scores', 'Có thể quản lý điểm môn học')], 'verbose_name': 'subject', 'verbose_name_plural': 'subjects'},
        ),
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_departments', to='app_home.department'),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_subjects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_semesters', to='app_semester.semester', verbose_name='Học kỳ'),
        ),
    ]
