<<<<<<< Updated upstream
# Generated by Django 4.2.7 on 2025-06-25 09:13
=======
# Generated by Django 4.2.7 on 2025-06-19 16:04
>>>>>>> Stashed changes

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Đăng nhập'), ('logout', 'Đăng xuất'), ('create', 'Tạo mới'), ('update', 'Cập nhật'), ('delete', 'Xóa'), ('view', 'Xem')], max_length=10)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
        ),
    ]
