# Generated by Django 4.2.7 on 2025-05-28 09:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Đã xóa')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa')),
                ('teacher_id', models.CharField(default='GV001', max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Mã giảng viên')),
                ('first_name', models.CharField(default='Tên', max_length=100, verbose_name='Tên')),
                ('last_name', models.CharField(default='Họ', max_length=100, verbose_name='Họ')),
                ('email', models.EmailField(default='teacher@example.com', max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(default='0123456789', max_length=15, unique=True, verbose_name='Số điện thoại')),
                ('date_of_birth', models.DateField(default=datetime.date.today, help_text='Định dạng: YYYY-MM-DD', verbose_name='Ngày sinh')),
                ('gender', models.CharField(choices=[('M', 'Nam'), ('F', 'Nữ'), ('O', 'Khác')], default='M', max_length=1, verbose_name='Giới tính')),
                ('address', models.TextField(default='Địa chỉ mặc định', verbose_name='Địa chỉ')),
                ('degree', models.CharField(choices=[('bachelor', 'Cử nhân'), ('master', 'Thạc sĩ'), ('phd', 'Tiến sĩ'), ('professor', 'Giáo sư')], default='master', max_length=20, verbose_name='Học vị')),
                ('specialization', models.CharField(default='Chưa xác định', max_length=200, verbose_name='Chuyên ngành')),
                ('years_of_experience', models.PositiveIntegerField(default=0, verbose_name='Số năm kinh nghiệm')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='teacher_profiles/', verbose_name='Ảnh đại diện')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Tiểu sử')),
                ('status', models.CharField(choices=[('active', 'Đang giảng dạy'), ('inactive', 'Tạm nghỉ'), ('retired', 'Đã nghỉ hưu'), ('on_leave', 'Nghỉ phép')], default='active', max_length=20, verbose_name='Trạng thái')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_teachers', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Người xóa')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_departments', to='app_home.department')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_teachers', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'teacher',
                'verbose_name_plural': 'teachers',
                'ordering': ['last_name', 'first_name'],
                'permissions': [('can_view_teacher_details', 'Có thể xem thông tin giảng viên'), ('can_manage_teacher', 'Có thể quản lý giảng viên'), ('can_view_teacher_schedule', 'Có thể xem lịch giảng dạy'), ('can_manage_teacher_schedule', 'Có thể quản lý lịch giảng dạy')],
            },
        ),
    ]
