# Generated by Django 4.2.7 on 2025-06-25 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_department", "0001_initial"),
        ("app_semester", "0001_initial"),
        ("app_class", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "schedule_id",
                    models.CharField(
                        default="LH001",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Mã lịch học",
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("mon", "Thứ Hai"),
                            ("tue", "Thứ Ba"),
                            ("wed", "Thứ Tư"),
                            ("thu", "Thứ Năm"),
                            ("fri", "Thứ Sáu"),
                            ("sat", "Thứ Bảy"),
                            ("sun", "Chủ Nhật"),
                        ],
                        max_length=3,
                        verbose_name="Ngày trong tuần",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Giờ bắt đầu")),
                ("end_time", models.TimeField(verbose_name="Giờ kết thúc")),
                ("room", models.CharField(default="P101", max_length=50, verbose_name="Phòng học")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Đang hoạt động"),
                            ("inactive", "Không hoạt động"),
                            ("pending", "Đang chờ duyệt"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Đang hoạt động")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="Đã xóa")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật")),
                (
                    "class_assigned",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="app_class.class",
                        verbose_name="Lớp học",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schedules",
                        to="app_department.department",
                        verbose_name="Khoa",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="app_semester.semester",
                        verbose_name="Học kỳ",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teaching_schedules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Giảng viên",
                    ),
                ),
            ],
            options={
                "verbose_name": "schedule",
                "verbose_name_plural": "schedules",
                "ordering": ["day_of_week", "start_time"],
                "permissions": [
                    ("can_view_schedule", "Có thể xem lịch học"),
                    ("can_manage_schedule", "Có thể quản lý lịch học"),
                ],
            },
        ),
    ]
