# Generated by Django 4.2.7 on 2025-05-20 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_score', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['-created_at'], 'permissions': [('can_view_score_details', 'Có thể xem thông tin điểm số'), ('can_manage_score', 'Có thể quản lý điểm số'), ('can_view_score_statistics', 'Có thể xem thống kê điểm số'), ('can_export_score', 'Có thể xuất điểm số')], 'verbose_name': 'score', 'verbose_name_plural': 'scores'},
        ),
        migrations.AddField(
            model_name='score',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='score',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_scores', to=settings.AUTH_USER_MODEL),
        ),
    ]
