# Generated by Django 4.2.7 on 2025-05-15 04:14

import app_class.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_subject', '0001_initial'),
        ('app_teacher', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_class', '0001_initial'),
        ('app_semester', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='class',
            name='semester',
            field=models.ForeignKey(default=app_class.models.get_default_semester, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='app_semester.semester', verbose_name='Học kỳ'),
        ),
        migrations.AddField(
            model_name='class',
            name='subject',
            field=models.ForeignKey(default=app_class.models.get_default_subject, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='app_subject.subject', verbose_name='Môn học'),
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='app_teacher.teacher', verbose_name='Giảng viên'),
        ),
    ]
