# Generated by Django 4.2.7 on 2025-05-20 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_class', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['name'], 'permissions': [('can_view_class_details', 'Có thể xem thông tin lớp học'), ('can_manage_class', 'Có thể quản lý lớp học'), ('can_view_class_scores', 'Có thể xem điểm lớp học'), ('can_manage_class_scores', 'Có thể quản lý điểm lớp học'), ('can_view_class_enrollments', 'Có thể xem danh sách đăng ký lớp học'), ('can_manage_class_enrollments', 'Có thể quản lý danh sách đăng ký lớp học')], 'verbose_name': 'class', 'verbose_name_plural': 'classes'},
        ),
    ]
