# Generated by Django 4.2.7 on 2025-05-20 02:28

import app_class.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0002_alter_user_options_user_address_user_is_deleted_and_more'),
        ('app_semester', '0002_alter_semester_options_semester_is_deleted_and_more'),
        ('app_teacher', '0002_alter_teacher_options_teacher_department_and_more'),
        ('app_subject', '0003_alter_subject_options_subject_department_and_more'),
        ('app_class', '0003_alter_class_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_departments', to='app_home.department'),
        ),
        migrations.AddField(
            model_name='class',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='class',
            name='subjects',
            field=models.ManyToManyField(related_name='class_subject_sets', to='app_subject.subject'),
        ),
        migrations.AddField(
            model_name='class',
            name='teachers',
            field=models.ManyToManyField(related_name='class_teacher_sets', to='app_teacher.teacher'),
        ),
        migrations.AddField(
            model_name='class',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='class',
            name='semester',
            field=models.ForeignKey(default=app_class.models.get_default_semester, on_delete=django.db.models.deletion.CASCADE, related_name='class_semesters', to='app_semester.semester', verbose_name='Học kỳ'),
        ),
        migrations.AlterField(
            model_name='class',
            name='subject',
            field=models.ForeignKey(default=app_class.models.get_default_subject, on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='app_subject.subject', verbose_name='Môn học'),
        ),
        migrations.AlterField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teachers', to='app_teacher.teacher', verbose_name='Giảng viên'),
        ),
    ]
