# Generated by Django 4.2.7 on 2025-06-19 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "class_id",
                    models.CharField(
                        default="L001", max_length=20, unique=True, verbose_name="Mã lớp"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Lớp mặc định", max_length=200, verbose_name="Tên lớp"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True, verbose_name="Mô tả")),
                ("credits", models.PositiveIntegerField(default=3, verbose_name="Số tín chỉ")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Đang hoạt động"),
                            ("inactive", "Không hoạt động"),
                            ("pending", "Đang chờ duyệt"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Đang hoạt động")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="Đã xóa")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật")),
            ],
            options={
                "verbose_name": "class",
                "verbose_name_plural": "classes",
                "ordering": ["name"],
                "permissions": [
                    ("can_view_class_details", "Có thể xem thông tin lớp học"),
                    ("can_manage_class", "Có thể quản lý lớp học"),
                    ("can_view_class_scores", "Có thể xem điểm lớp học"),
                    ("can_manage_class_scores", "Có thể quản lý điểm lớp học"),
                    ("can_view_class_enrollments", "Có thể xem danh sách đăng ký lớp học"),
                    ("can_manage_class_enrollments", "Có thể quản lý danh sách đăng ký lớp học"),
                ],
            },
        ),
    ]
