<<<<<<< Updated upstream
# Generated by Django 4.2.7 on 2025-06-25 09:13
=======
# Generated by Django 4.2.7 on 2025-06-19 16:04
>>>>>>> Stashed changes

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(default='L001', max_length=20, unique=True, verbose_name='Mã lớp')),
                ('name', models.CharField(default='Lớp mặc định', max_length=200, verbose_name='Tên lớp')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('credits', models.PositiveIntegerField(default=3, verbose_name='Số tín chỉ')),
                ('status', models.CharField(choices=[('active', 'Đang hoạt động'), ('inactive', 'Không hoạt động'), ('pending', 'Đang chờ duyệt')], default='active', max_length=20, verbose_name='Trạng thái')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Đã xóa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
        ),
    ]
