<<<<<<< Updated upstream
# Generated by Django 4.2.7 on 2025-06-25 09:13
=======
# Generated by Django 4.2.7 on 2025-06-19 16:04
>>>>>>> Stashed changes

import api.app_class.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< Updated upstream
        ("app_department", "0001_initial"),
        ("app_semester", "0001_initial"),
        ("app_subject", "0001_initial"),
        ("app_class", "0001_initial"),
=======
        ('app_semester', '0001_initial'),
        ('app_class', '0001_initial'),
        ('app_department', '0001_initial'),
        ('app_subject', '0001_initial'),
>>>>>>> Stashed changes
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_departments', to='app_department.department', verbose_name='Khoa'),
        ),
        migrations.AddField(
            model_name='class',
            name='semester',
            field=models.ForeignKey(default=api.app_class.models.get_default_semester, on_delete=django.db.models.deletion.CASCADE, related_name='class_semesters', to='app_semester.semester', verbose_name='Học kỳ'),
        ),
        migrations.AddField(
            model_name='class',
            name='subject',
            field=models.ForeignKey(default=api.app_class.models.get_default_subject, on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='app_subject.subject', verbose_name='Môn học'),
        ),
        migrations.AddField(
            model_name='class',
            name='subjects',
            field=models.ManyToManyField(related_name='class_subject_sets', to='app_subject.subject'),
        ),
    ]
