<<<<<<< Updated upstream
# Generated by Django 4.2.7 on 2025-06-25 09:13
=======
# Generated by Django 4.2.7 on 2025-06-19 16:04
>>>>>>> Stashed changes

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< Updated upstream
        ("app_class", "0002_initial"),
        ("app_teacher", "0001_initial"),
=======
        ('app_teacher', '0001_initial'),
        ('app_class', '0002_initial'),
>>>>>>> Stashed changes
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teachers', to='app_teacher.teacher', verbose_name='Giảng viên'),
        ),
        migrations.AddField(
            model_name='class',
            name='teachers',
            field=models.ManyToManyField(related_name='class_teacher_sets', to='app_teacher.teacher'),
        ),
    ]
