# Generated by Django 4.2.7 on 2025-06-25 09:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_department", "0002_initial"),
        ("app_class", "0003_initial"),
        ("app_score", "0001_initial"),
        ("app_subject", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "student_id",
                    models.CharField(max_length=20, unique=True, verbose_name="Student ID"),
                ),
                ("first_name", models.CharField(default="Tên", max_length=100, verbose_name="Tên")),
                ("last_name", models.CharField(default="Họ", max_length=100, verbose_name="Họ")),
                (
                    "email",
                    models.EmailField(
                        default="student@example.com",
                        max_length=254,
                        unique=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="", max_length=15, verbose_name="Số điện thoại"
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        default=datetime.date.today,
                        help_text="Định dạng: YYYY-MM-DD",
                        verbose_name="Ngày sinh",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Nam"), ("F", "Nữ"), ("O", "Khác")],
                        default="M",
                        max_length=1,
                        verbose_name="Giới tính",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Đang hoạt động")),
                ("address", models.TextField(default="Địa chỉ mặc định", verbose_name="Địa chỉ")),
                (
                    "city",
                    models.CharField(default="Hà Nội", max_length=100, verbose_name="Thành phố"),
                ),
                (
                    "state",
                    models.CharField(default="Hà Nội", max_length=100, verbose_name="Tỉnh/Thành"),
                ),
                (
                    "postal_code",
                    models.CharField(default="100000", max_length=20, verbose_name="Mã bưu điện"),
                ),
                (
                    "country",
                    models.CharField(default="Việt Nam", max_length=100, verbose_name="Quốc gia"),
                ),
                ("enrollment_date", models.DateField(verbose_name="Enrollment Date")),
                (
                    "graduation_date",
                    models.DateField(blank=True, null=True, verbose_name="Graduation Date"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Đang học"),
                            ("graduated", "Đã tốt nghiệp"),
                            ("suspended", "Bị đình chỉ"),
                            ("withdrawn", "Đã rút học bạ"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "major",
                    models.CharField(
                        default="Chưa xác định", max_length=100, verbose_name="Chuyên ngành"
                    ),
                ),
                (
                    "minor",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Chuyên ngành phụ"
                    ),
                ),
                (
                    "gpa",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=3, verbose_name="Điểm trung bình"
                    ),
                ),
                (
                    "credits_earned",
                    models.PositiveIntegerField(default=0, verbose_name="Số tín chỉ đã tích lũy"),
                ),
                (
                    "credits_attempted",
                    models.PositiveIntegerField(default=0, verbose_name="Số tín chỉ đã đăng ký"),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(
                        default="Người thân",
                        max_length=100,
                        verbose_name="Tên người liên hệ khẩn cấp",
                    ),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(
                        default="0123456789", max_length=15, verbose_name="Số điện thoại khẩn cấp"
                    ),
                ),
                (
                    "emergency_contact_relationship",
                    models.CharField(default="Gia đình", max_length=50, verbose_name="Mối quan hệ"),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="student_profiles/",
                        verbose_name="Ảnh đại diện",
                    ),
                ),
                (
                    "student_id_card",
                    models.CharField(
                        default="SV001", max_length=20, unique=True, verbose_name="Mã thẻ sinh viên"
                    ),
                ),
                (
                    "blood_type",
                    models.CharField(blank=True, max_length=5, null=True, verbose_name="Nhóm máu"),
                ),
                (
                    "medical_conditions",
                    models.TextField(blank=True, null=True, verbose_name="Tình trạng sức khỏe"),
                ),
                ("allergies", models.TextField(blank=True, null=True, verbose_name="Dị ứng")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật")),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Ngày xóa"),
                ),
                ("is_deleted", models.BooleanField(default=False, verbose_name="Đã xóa")),
                (
                    "class_assigned",
                    models.ManyToManyField(
                        blank=True,
                        related_name="student_classes",
                        to="app_class.class",
                        verbose_name="Lớp học",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="app_department.department",
                    ),
                ),
                (
                    "scores",
                    models.ManyToManyField(
                        blank=True,
                        related_name="student_score_sets",
                        to="app_score.score",
                        verbose_name="Điểm số",
                    ),
                ),
                (
                    "subjects",
                    models.ManyToManyField(
                        blank=True,
                        related_name="student_subjects",
                        to="app_subject.subject",
                        verbose_name="Môn học",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
                "ordering": ["student_id"],
                "permissions": [
                    ("can_view_student_details", "Có thể xem thông tin sinh viên"),
                    ("can_manage_student", "Có thể quản lý sinh viên"),
                    ("can_view_student_grades", "Có thể xem điểm sinh viên"),
                    ("can_manage_student_enrollment", "Có thể quản lý đăng ký của sinh viên"),
                ],
            },
        ),
    ]
