# Generated by Django 4.2.7 on 2025-06-18 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='student',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='student',
            name='updated_by',
        ),
    ]
