# Generated by Django 4.2.7 on 2025-05-26 03:48

import app_score.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_semester', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Đã xóa')),
                ('midterm_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Điểm giữa kỳ')),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Điểm cuối kỳ')),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Tổng điểm')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('status', models.CharField(choices=[('active', 'Đang hoạt động'), ('inactive', 'Không hoạt động'), ('pending', 'Đang chờ duyệt')], default='active', max_length=20, verbose_name='Trạng thái')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scores', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(default=app_score.models.get_default_semester, on_delete=django.db.models.deletion.CASCADE, related_name='semester_scores', to='app_semester.semester', verbose_name='Học kỳ')),
            ],
            options={
                'verbose_name': 'score',
                'verbose_name_plural': 'scores',
                'ordering': ['-created_at'],
                'permissions': [('can_view_score_details', 'Có thể xem thông tin điểm số'), ('can_manage_score', 'Có thể quản lý điểm số'), ('can_view_score_statistics', 'Có thể xem thống kê điểm số'), ('can_export_score', 'Có thể xuất điểm số')],
            },
        ),
    ]
