# Generated by Django 4.2.7 on 2025-06-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "department_id",
                    models.AutoField(primary_key=True, serialize=False, verbose_name="ID khoa"),
                ),
                ("department_name", models.CharField(max_length=200, verbose_name="Tên khoa")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Mô tả")),
                ("is_active", models.BooleanField(default=True, verbose_name="Đang hoạt động")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="Đã xóa")),
            ],
        ),
    ]
