# Generated by Django 4.2.7 on 2025-06-19 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Tên khoa")),
                ("code", models.CharField(max_length=20, unique=True, verbose_name="Mã khoa")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Mô tả")),
                ("is_active", models.BooleanField(default=True, verbose_name="Đang hoạt động")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="Đã xóa")),
            ],
            options={
                "verbose_name": "department",
                "verbose_name_plural": "departments",
                "db_table": "app_home_department",
                "ordering": ["name"],
                "permissions": [
                    ("can_manage_department", "Có thể quản lý khoa"),
                    ("can_view_department", "Có thể xem thông tin khoa"),
                ],
            },
        ),
    ]
