# Generated by Django 4.2.7 on 2025-05-20 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_semester', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['-start_date'], 'permissions': [('can_view_semester', 'Có thể xem học kỳ'), ('can_manage_semester', 'Có thể quản lý học kỳ'), ('can_view_semester_schedule', 'Có thể xem lịch học kỳ'), ('can_manage_semester_registration', 'Có thể quản lý đăng ký học kỳ')], 'verbose_name': 'semester', 'verbose_name_plural': 'semesters'},
        ),
        migrations.AddField(
            model_name='semester',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='semester',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_semesters', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật'),
        ),
    ]
