# Generated by Django 4.2.7 on 2025-05-15 04:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(default=django.utils.timezone.now, verbose_name='Ngày đăng ký')),
                ('status', models.CharField(choices=[('active', 'Đang hoạt động'), ('inactive', 'Không hoạt động'), ('pending', 'Đang chờ duyệt')], default='active', max_length=20, verbose_name='Trạng thái')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Đăng ký',
                'verbose_name_plural': 'Đăng ký',
                'ordering': ['-created_at'],
                'permissions': [('can_view_enrollment_details', 'Có thể xem thông tin đăng ký'), ('can_manage_enrollment', 'Có thể quản lý đăng ký'), ('can_view_enrollment_statistics', 'Có thể xem thống kê đăng ký'), ('can_export_enrollment', 'Có thể xuất đăng ký')],
            },
        ),
    ]
