# Generated by Django 4.2.7 on 2025-05-15 04:14

import app_enrollment.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_enrollment', '0001_initial'),
        ('app_student', '0001_initial'),
        ('app_semester', '0001_initial'),
        ('app_subject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='semester',
            field=models.ForeignKey(default=app_enrollment.models.get_default_semester, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='app_semester.semester', verbose_name='Học kỳ'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(default=app_enrollment.models.get_default_student, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='app_student.student', verbose_name='Sinh viên'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='subject',
            field=models.ForeignKey(default=app_enrollment.models.get_default_subject, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='app_subject.subject', verbose_name='Môn học'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'subject', 'semester')},
        ),
    ]
