# Generated by Django 4.2.7 on 2025-05-20 02:28

import app_enrollment.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_semester', '0002_alter_semester_options_semester_is_deleted_and_more'),
        ('app_student', '0001_initial'),
        ('app_class', '0003_alter_class_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_subject', '0002_subject_semester'),
        ('app_enrollment', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-created_at'], 'permissions': [('can_view_enrollment_details', 'Có thể xem thông tin đăng ký'), ('can_manage_enrollment', 'Có thể quản lý đăng ký'), ('can_view_enrollment_statistics', 'Có thể xem thống kê đăng ký'), ('can_export_enrollment', 'Có thể xuất đăng ký')], 'verbose_name': 'enrollment', 'verbose_name_plural': 'enrollments'},
        ),
        migrations.AddField(
            model_name='enrollment',
            name='class_obj',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='class_enrollments', to='app_class.class'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='semester',
            field=models.ForeignKey(default=app_enrollment.models.get_default_semester, on_delete=django.db.models.deletion.CASCADE, related_name='semester_enrollments', to='app_semester.semester', verbose_name='Học kỳ'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(default=app_enrollment.models.get_default_student, on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='app_student.student', verbose_name='Sinh viên'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='subject',
            field=models.ForeignKey(default=app_enrollment.models.get_default_subject, on_delete=django.db.models.deletion.CASCADE, related_name='subject_enrollments', to='app_subject.subject', verbose_name='Môn học'),
        ),
    ]
