# Generated by Django 4.2.7 on 2025-05-20 02:36

import app_enrollment.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_semester', '0002_alter_semester_options_semester_is_deleted_and_more'),
        ('app_student', '0002_alter_student_options_student_department_and_more'),
        ('app_subject', '0003_alter_subject_options_subject_department_and_more'),
        ('app_enrollment', '0003_alter_enrollment_options_enrollment_class_obj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='semester',
            field=models.ForeignKey(blank=True, default=app_enrollment.models.get_default_semester, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semester_enrollments', to='app_semester.semester', verbose_name='Học kỳ'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(blank=True, default=app_enrollment.models.get_default_student, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='app_student.student', verbose_name='Sinh viên'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='subject',
            field=models.ForeignKey(blank=True, default=app_enrollment.models.get_default_subject, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_enrollments', to='app_subject.subject', verbose_name='Môn học'),
        ),
    ]
