# Generated by Django 4.2.7 on 2025-05-20 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_class', '0004_class_department_class_is_deleted_class_subjects_and_more'),
        ('app_score', '0003_alter_score_options_score_is_deleted_and_more'),
        ('app_home', '0002_alter_user_options_user_address_user_is_deleted_and_more'),
        ('app_subject', '0003_alter_subject_options_subject_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last_name', 'first_name'], 'permissions': [('can_view_student_details', 'Có thể xem thông tin sinh viên'), ('can_manage_student', 'Có thể quản lý sinh viên'), ('can_view_student_grades', 'Có thể xem điểm sinh viên'), ('can_manage_student_enrollment', 'Có thể quản lý đăng ký của sinh viên')], 'verbose_name': 'student', 'verbose_name_plural': 'students'},
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_departments', to='app_home.department'),
        ),
        migrations.AddField(
            model_name='student',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_assigned',
            field=models.ManyToManyField(blank=True, related_name='student_classes', to='app_class.class', verbose_name='Lớp học'),
        ),
        migrations.AlterField(
            model_name='student',
            name='scores',
            field=models.ManyToManyField(blank=True, related_name='student_score_sets', to='app_score.score', verbose_name='Điểm số'),
        ),
        migrations.AlterField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='student_subjects', to='app_subject.subject', verbose_name='Môn học'),
        ),
    ]
