# Generated by Django 4.2.7 on 2025-05-20 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0002_alter_user_options_user_address_user_is_deleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['last_name', 'first_name'], 'permissions': [('can_view_teacher_details', 'Có thể xem thông tin giảng viên'), ('can_manage_teacher', 'Có thể quản lý giảng viên'), ('can_view_teacher_schedule', 'Có thể xem lịch giảng dạy'), ('can_manage_teacher_schedule', 'Có thể quản lý lịch giảng dạy')], 'verbose_name': 'teacher', 'verbose_name_plural': 'teachers'},
        ),
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_departments', to='app_home.department'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_teachers', to=settings.AUTH_USER_MODEL),
        ),
    ]
