# Generated by Django 4.2.7 on 2025-06-26 07:01

import api.app_enrollment.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_class", "0002_initial"),
        ("app_semester", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "enrollment_id",
                    models.CharField(
                        default="ENR001",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Mã đăng ký",
                    ),
                ),
                (
                    "enrollment_date",
                    models.DateField(default=datetime.date.today, verbose_name="Ngày đăng ký"),
                ),
                (
                    "academic_year",
                    models.CharField(default="2023-2024", max_length=10, verbose_name="Năm học"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Chờ xử lý"),
                            ("approved", "Đã duyệt"),
                            ("rejected", "Từ chối"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Đang hoạt động")),
                ("notes", models.TextField(blank=True, null=True, verbose_name="Ghi chú")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="Đã xóa")),
                (
                    "class_obj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_enrollments",
                        to="app_class.class",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        blank=True,
                        default=api.app_enrollment.models.get_default_semester,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semester_enrollments",
                        to="app_semester.semester",
                        verbose_name="Học kỳ",
                    ),
                ),
            ],
        ),
    ]
