<<<<<<< Updated upstream
# Generated by Django 4.2.7 on 2025-06-25 09:13
=======
# Generated by Django 4.2.7 on 2025-06-19 16:04
>>>>>>> Stashed changes

import api.app_enrollment.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_semester', '0001_initial'),
        ('app_class', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(default=datetime.date.today, verbose_name='Ngày đăng ký')),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Đã xóa')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_enrollments', to='app_class.class')),
                ('semester', models.ForeignKey(blank=True, default=api.app_enrollment.models.get_default_semester, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semester_enrollments', to='app_semester.semester', verbose_name='Học kỳ')),
            ],
        ),
    ]
