# Generated by Django 4.2.7 on 2025-06-19 04:47

import api.app_enrollment.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_student", "0001_initial"),
        ("app_subject", "0001_initial"),
        ("app_enrollment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="student",
            field=models.ForeignKey(
                blank=True,
                default=api.app_enrollment.models.get_default_student,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_enrollments",
                to="app_student.student",
                verbose_name="Sinh viên",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                default=api.app_enrollment.models.get_default_subject,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subject_enrollments",
                to="app_subject.subject",
                verbose_name="Môn học",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together={("student", "subject", "semester")},
        ),
    ]
