# Generated by Django 4.2.20 on 2025-06-02 07:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Đã xóa')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa')),
                ('semester_id', models.CharField(default='HK001', max_length=20, primary_key=True, serialize=False, verbose_name='Mã học kỳ')),
                ('name', models.CharField(default='Học kỳ 1', max_length=100, verbose_name='Tên học kỳ')),
                ('academic_year', models.CharField(default='2023-2024', max_length=9, verbose_name='Năm học')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(default=datetime.date.today, verbose_name='Ngày kết thúc')),
                ('registration_start', models.DateField(default=datetime.date.today, verbose_name='Ngày bắt đầu đăng ký')),
                ('registration_end', models.DateField(default=datetime.date.today, verbose_name='Ngày kết thúc đăng ký')),
                ('add_drop_deadline', models.DateField(default=datetime.date.today, verbose_name='Hạn chót thêm/xóa môn')),
                ('status', models.CharField(choices=[('upcoming', 'Sắp tới'), ('current', 'Đang diễn ra'), ('completed', 'Đã kết thúc'), ('cancelled', 'Đã hủy')], default='upcoming', max_length=20, verbose_name='Trạng thái')),
                ('total_credits', models.PositiveIntegerField(default=0, verbose_name='Tổng số tín chỉ')),
                ('min_credits', models.PositiveIntegerField(default=12, verbose_name='Số tín chỉ tối thiểu')),
                ('max_credits', models.PositiveIntegerField(default=24, verbose_name='Số tín chỉ tối đa')),
                ('tuition_deadline', models.DateField(default=datetime.date.today, verbose_name='Hạn nộp học phí')),
                ('late_fee_start', models.DateField(default=datetime.date.today, verbose_name='Ngày bắt đầu tính phí trễ')),
                ('late_fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Phí trễ hạn')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_semesters', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Người xóa')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_semesters', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật')),
            ],
            options={
                'verbose_name': 'semester',
                'verbose_name_plural': 'semesters',
                'ordering': ['-start_date'],
                'permissions': [('can_view_semester', 'Có thể xem học kỳ'), ('can_manage_semester', 'Có thể quản lý học kỳ'), ('can_view_semester_schedule', 'Có thể xem lịch học kỳ'), ('can_manage_semester_registration', 'Có thể quản lý đăng ký học kỳ')],
            },
        ),
    ]
