# Generated by Django 4.2.7 on 2025-06-26 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "semester_id",
                    models.CharField(
                        default="HK001",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Mã học kỳ",
                    ),
                ),
                (
                    "semester_name",
                    models.CharField(default="Học kỳ 1", max_length=100, verbose_name="Tên học kỳ"),
                ),
                (
                    "academic_year",
                    models.CharField(default="2023-2024", max_length=9, verbose_name="Năm học"),
                ),
                (
                    "start_date",
                    models.DateField(default=datetime.date.today, verbose_name="Ngày bắt đầu"),
                ),
                (
                    "end_date",
                    models.DateField(default=datetime.date.today, verbose_name="Ngày kết thúc"),
                ),
                (
                    "registration_start",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Ngày bắt đầu đăng ký"
                    ),
                ),
                (
                    "registration_end",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Ngày kết thúc đăng ký"
                    ),
                ),
                (
                    "add_drop_deadline",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Hạn chót thêm/xóa môn"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Sắp tới"),
                            ("current", "Đang diễn ra"),
                            ("completed", "Đã kết thúc"),
                            ("cancelled", "Đã hủy"),
                        ],
                        default="upcoming",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "total_credits",
                    models.PositiveIntegerField(default=0, verbose_name="Tổng số tín chỉ"),
                ),
                (
                    "min_credits",
                    models.PositiveIntegerField(default=12, verbose_name="Số tín chỉ tối thiểu"),
                ),
                (
                    "max_credits",
                    models.PositiveIntegerField(default=24, verbose_name="Số tín chỉ tối đa"),
                ),
                (
                    "tuition_deadline",
                    models.DateField(default=datetime.date.today, verbose_name="Hạn nộp học phí"),
                ),
                (
                    "late_fee_start",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Ngày bắt đầu tính phí trễ"
                    ),
                ),
                (
                    "late_fee_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="Phí trễ hạn"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True, verbose_name="Mô tả")),
                ("notes", models.TextField(blank=True, null=True, verbose_name="Ghi chú")),
                ("is_active", models.BooleanField(default=True, verbose_name="Đang hoạt động")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="Đã xóa")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật")),
            ],
        ),
    ]
